change = float(input())
change_in_coins = change * 100
change_in_coins = int(change_in_coins)
count_coins= 0
coins = change_in_coins // 200
count_coins += coins
change_in_coins = change_in_coins % 200
coins = change_in_coins // 100
count_coins += coins
change_in_coins = change_in_coins % 100
coins = change_in_coins // 50
count_coins += coins
change_in_coins = change_in_coins % 50
coins = change_in_coins // 20
count_coins += coins
change_in_coins = change_in_coins % 20
coins = change_in_coins // 10
count_coins += coins
change_in_coins = change_in_coins % 10
coins = change_in_coins // 5
count_coins += coins
change_in_coins = change_in_coins % 5
coins = change_in_coins // 2
count_coins += coins
change_in_coins = change_in_coins % 2
coins = change_in_coins // 1
count_coins += coins
change_in_coins = change_in_coins % 1
print(count_coins)