title_article = input()
content = input()
comments = input()
print("<h1>")
print(f"    {title_article}")
print("</h1>")
print("<article>")
print(f"    {content}")
print("</article>")
while not comments == "end of comments":
    print("<div>")
    print(f"    {comments}")
    print("</div>")
    comments = input()