sequence_of_numbers = input().split(', ')
positive_num = ', '.join([digit for digit in sequence_of_numbers if int(digit) >= 0])
negative_num = ', '.join([digit for digit in sequence_of_numbers if int(digit) < 0])
even_num = ', '.join([digit for digit in sequence_of_numbers if int(digit) % 2 == 0])
odd_num = ', '.join([digit for digit in sequence_of_numbers if int(digit) % 2 == 1])
print(f'Positive: {positive_num}')
print(f'Negative: {negative_num}')
print(f'Even: {even_num}')
print(f'Odd: {odd_num}')